In [ ]:
import numpy as np

In [ ]:
a=np.array([21,74])

In [ ]:
print(a,type(a),a.shape)

[21 74] <class 'numpy.ndarray'> (2,)


In [ ]:
b=np.array([[21,74],[74,21]])

In [ ]:
print(b,b.shape)

[[21 74]
 [74 21]] (2, 2)


In [ ]:
a=np.zeros((3,3))

In [ ]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d=np.eye(4)

In [ ]:
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
e = np.random.random((4,5))

In [ ]:
print(e)

[[0.97772988 0.2251866  0.2887815  0.33256567 0.92971491]
 [0.06909586 0.33601932 0.2181674  0.77295434 0.00787525]
 [0.37092562 0.7586433  0.78580136 0.81930646 0.50574048]
 [0.97920328 0.58107914 0.39205191 0.67789298 0.23180426]]


In [ ]:
z = np.zeros((4,4))

In [ ]:
z[:,1]=5
z[2,:]=7
print(z)

[[0. 5. 0. 0.]
 [0. 5. 0. 0.]
 [7. 7. 7. 7.]
 [0. 5. 0. 0.]]


In [ ]:
print(np.sqrt(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.array([1,2,3])

In [ ]:
np.random.shuffle(a)

In [ ]:
print(a)

[2 3 1]


In [ ]:
np.random.random((3,4))

array([[0.11145932, 0.06630322, 0.96961491, 0.56900939],
       [0.00630919, 0.84212449, 0.6973172 , 0.12737232],
       [0.37775883, 0.97219425, 0.08069124, 0.72724679]])

In [ ]:
np.random.randn(2,4)
# use seed to make pseudo random constant generator

array([[ 0.20143717,  0.41995792,  1.26992234, -0.41606199],
       [ 0.90411648, -0.1304739 , -0.88571068,  1.9453219 ]])

In [ ]:
a.reshape(3,1)

array([[2],
       [3],
       [1]])

In [ ]:
print(np.min(a))
print(np.min(a,axis=0))

1
1


In [ ]:
print(np.mean(a))

2.0


In [ ]:
print(np.median(a))

2.0


In [ ]:
# average vs mean -- average has weights 
w = np.array([1,2,3])
b = np.array([5,6,7])
print(np.average(b,weights=w))

6.333333333333333


In [ ]:
# standard deviation
print(np.std(b))

0.816496580927726


In [ ]:
print(np.var(b))